# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StqryCli < Formula
  desc "STQRY CLI - manage collections, screens, media, and content"
  homepage "https://github.com/mytours/stqry-cli"
  version "0.10.38"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mytours/stqry-cli/releases/download/v0.10.38/stqry-cli_darwin_amd64.tar.gz"
      sha256 "2a8c73f946444a3937bfc3704576bf2a895449532712c313ca0962a5c22d300e"

      define_method(:install) do
        bin.install "stqry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mytours/stqry-cli/releases/download/v0.10.38/stqry-cli_darwin_arm64.tar.gz"
      sha256 "4304d4df06353c890cfdce2a1daa6f9e90feb008f4afbaada302b45cff4086c8"

      define_method(:install) do
        bin.install "stqry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mytours/stqry-cli/releases/download/v0.10.38/stqry-cli_linux_amd64.tar.gz"
      sha256 "0cd6f5bb00024535a94f310f754035277f4048f3a0876012600aff6ac447cdf1"
      define_method(:install) do
        bin.install "stqry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mytours/stqry-cli/releases/download/v0.10.38/stqry-cli_linux_arm64.tar.gz"
      sha256 "6727de62f2ac021755aa47f62800bffafedf8f7407b8deece2c0f8f2c2ef5617"
      define_method(:install) do
        bin.install "stqry"
      end
    end
  end

  test do
    system "#{bin}/stqry", "--version"
  end
end
